import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "@/components/layout/Header";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { getPublicCollection } from "@/lib/catalog/cloudflare-repository";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const result = await getPublicCollection(slug); return result ? { title: result.collection.nameEn, description: result.collection.description || `Explore ${result.collection.nameEn} by Avoocado Studio.` } : {}; }

export default async function CollectionPage({ params }: { params: Promise<{ slug: string }> }) {
    const { slug } = await params; const result = await getPublicCollection(slug); if (!result) notFound(); const { collection, designs } = result;
    return <main><Header /><section className="container pb-20 pt-44 md:pt-52"><div className="grid gap-12 md:grid-cols-[1.1fr_0.9fr] md:items-end"><div><span className="text-xs font-medium uppercase tracking-[0.2em] text-[var(--color-primary)]">Collection / {collection.nameFa}</span><h1 className="mt-6 text-[clamp(4rem,9vw,10rem)] font-bold leading-[0.8] tracking-[-0.07em]">{collection.nameEn}</h1></div>{collection.description && <p className="max-w-md text-base leading-7 text-black/55">{collection.description}</p>}</div>{collection.coverImageKey && <div className="mt-16 aspect-[16/7] bg-neutral-100 bg-cover bg-center" style={{ backgroundImage: `url(${JSON.stringify(collection.coverImageKey)})` }} />}</section><section className="container pb-28"><div className="mb-10 flex justify-between border-b border-black/15 pb-5"><span className="text-sm">Pieces in this collection</span><span className="text-sm text-black/45">{designs.length} items</span></div>{designs.length ? <div className="grid gap-x-5 gap-y-14 sm:grid-cols-2 lg:grid-cols-3">{designs.map((design) => <Link href={`/t-shirts/${design.slug}`} className="group" key={design.id}><div className="aspect-[4/5] overflow-hidden bg-[#f1f0eb]">{design.artworkKey ? <img src={design.artworkKey} alt={design.name} className="h-full w-full object-contain transition-transform duration-500 group-hover:scale-[1.03]" /> : <div className="flex h-full items-center justify-center text-xs uppercase tracking-[0.16em] text-black/35">Artwork coming soon</div>}</div><div className="mt-5 flex justify-between gap-6"><div><h2 className="text-xl font-medium">{design.name}</h2><p className="mt-1 text-sm text-black/50">{collection.nameEn}</p></div><span className="whitespace-nowrap text-sm font-medium">{design.basePrice.toLocaleString("fa-IR")} تومان</span></div></Link>)}</div> : <div className="py-20 text-center"><p className="text-2xl font-medium">Designs are coming soon.</p><p className="mt-3 text-sm text-black/45">This collection is ready and its artworks will appear here as soon as they are published.</p></div>}</section><SiteFooter /></main>;
}
